### ISSUE TITLE
NavigatorIOS throwing errors 

### ISSUE THREAD

**Issue by guilhermedecampo** [catalinmiron/react-native-dribbble-app#10]
Hey @catalinmiron,

maybe this is interesting to you...
After some navigation through the app the red screen appeared.

Seems to be related with ios navigation.. I'm still in the early stage of learning. Hopefully I will be able to fix this soon. ;)

![screen shot 2015-08-15 at 5 04 20 pm](https://cloud.githubusercontent.com/assets/4806269/9290621/3dd96f52-4370-11e5-918d-01ae7da0f520.png)

Cheers!

**Comment by catalin-miron-hs** [comment]
@guilhermedecampo can you reproduce it ? 

I also mention that there is a known bug. 
**tl;dr**: You cannot view a shot from a player view

You can reproduce it by going to a `player` view, an clicking on a shot image. This is because the endpoint is not returning the same object, from `player` endpoint, as it returns from `shots` endpoint. I'll fix it as soon as I'll have some time.
